apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: vclusters.multicloud.environments
spec:
  group: multicloud.environments
  names:
    kind: vcluster
    plural: vclusters
  claimNames:
    kind: ClusterClaim
    plural: clusterclaims
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              clusterName:
                type: string
              namespace:
                type: string
            required:
            - clusterName
            - namespace